project:
  type: website

website:
  title: "IntegrativeBandit"
  navbar:
    left:
      - href: index.qmd
        text: Document
      - href: Demo.qmd
        text: Demo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

